# Ansible Collections Requirements
# Install these collections before running the playbook
# ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.windows
    version: ">=1.10.0"
  - name: community.general
    version: ">=5.0.0"
  - name: ansible.windows
    version: ">=1.10.0"
